services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: vpn
      POSTGRES_USER: vpn
      POSTGRES_PASSWORD: vpn
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    depends_on:
      - db
    environment:
      SECRET_KEY: "change-me"
      PORT: "5000"

      ADMIN_USERNAME: "admin"
      ADMIN_PASSWORD: "admin12345"

      LOG_PATH: "/tmp/app.log"

      DATABASE_URL: "postgresql+psycopg2://vpn:vpn@db:5432/vpn"

    ports:
      - "5051:5000"
    volumes:
      - ./_logs:/tmp

volumes:
  pgdata:
