services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: vpn
      POSTGRES_USER: vpn
      POSTGRES_PASSWORD: vpn
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U vpn -d vpn" ]
      interval: 2s
      timeout: 3s
      retries: 20

  web:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      SECRET_KEY: "change-me"
      PORT: "5000"

      ADMIN_USERNAME: "admin"
      ADMIN_PASSWORD: "admin12345"

      LOG_PATH: "/tmp/app.log"

      DATABASE_URL: "postgresql+psycopg2://vpn:vpn@db:5432/vpn"

    ports:
      - "5050:5000"
    volumes:
      - ./_logs:/tmp
